export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL";
export const LOGOUT = "LOGOUT";

// notes constant
export const GET_ALL_NOTE_REQUEST = "GET_ALL_NOTE_REQUEST";
export const GET_ALL_NOTE_REQUEST_SUCCESS = "GET_ALL_NOTE_REQUEST_SUCCESS";
export const GET_ALL_NOTE_REQUEST_FAILED = "GET_ALL_NOTE_REQUEST_FAILED";
export const GET_SINGLE_NOTE_REQUEST = "GET_SINGLE_NOTE_REQUEST";
export const GET_SINGLE_NOTE_REQUEST_SUCCESS =
  "GET_SINGLE_NOTE_REQUEST_SUCCESS";
export const GET_SINGLE_NOTE_REQUEST_FAILED = "GET_SINGLE_NOTE_REQUEST_FAILED";

export const CREATE_NOTE_REQUEST = "CREATE_NOTE_REQUEST";
export const CREATE_NOTE_REQUEST_SUCCESS = "CREATE_NOTE_REQUEST_SUCCESS";
export const CREATE_NOTE_REQUEST_FAILED = "CREATE_NOTE_REQUEST_FAILED";

export const UPDATE_NOTE_REQUEST = "UPDATE_NOTE_REQUEST";
export const UPDATE_NOTE_REQUEST_SUCCESS = "UPDATE_NOTE_REQUEST_SUCCESS";
export const UPDATE_NOTE_REQUEST_FAILED = "UPDATE_NOTE_REQUEST_FAILED";

export const DELETE_NOTE_REQUEST = "DELETE_NOTE_REQUEST";
export const DELETE_NOTE_REQUEST_SUCCESS = "DELETE_NOTE_REQUEST_SUCCESS";
export const DELETE_NOTE_REQUEST_FAILED = "DELETE_NOTE_REQUEST_FAILED";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_REQUEST_SUCCESS = "SIGN_UP_REQUEST_SUCCESS";
export const SIGN_UP_REQUEST_FAILED = "SIGN_UP_REQUEST_FAILED";

export const EDIT_REQUEST = "EDIT_REQUEST";
export const EDIT_REQUEST_SUCCESS = "EDIT_REQUEST_SUCCESS";
export const EDIT_REQUEST_FAILED = "EDIT_REQUEST_FAILED";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const DELETE_REQUEST_FAILED = "DELETE_REQUEST_FAILED";
